server:
   port: 8888
spring:
   cloud: 
      config:
         server:
           git:   
             refreshRate: 5      
             uri: https://github.com/in-the-keyhole/spring-cloud-configuration
             search-paths: 
              - '*ConfigrationFiles'


# Use file system backend for configurations
#spring:
#   profiles:
#      active: native 
#   cloud: 
#      config:
#         server:           
#            native:
#               searchLocations: file:///C:/Users/userid/git-repository/config-data         
